contentColumnType: string
fieldGroup: f33009e6-e6ee-48c3-9dc3-861195670ed1
handle: timelineType
instructions: ''
name: 'Timeline Type'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - National
        -
          - value
          - national
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Local
        -
          - value
          - local
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
